import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Discord | Your place to take and hang Out",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
 
        {children}

     

        
  <div className=" bg-black pt-20 pl-32">
    <ul className="flex justify-start items-start  bg-black  ">
      <li>
      <Image src="/flag-1.png" alt="flag-1" width={50} height={50}/>
      </li>
      <li className="text-white  px-3 pt-2">English</li>
      <li className="text-white pt-2">⌅</li>
      
    </ul>

    
  <ul className="flex gap-6 bg-black  mr-20">
      <li><Image src="/footer-1.png" alt="footer-1" width={20} height={20}/></li>
      <li><Image src="/footer-2.png" alt="footer-2" width={20} height={20}/></li>
      <li><Image src="/footer-3.png" alt="footer-3" width={20} height={20}/></li>
      <li><Image src="/footer-4.png" alt="footer-4" width={20} height={20}/></li>
      <li><Image src="/footer-5.png" alt="footer-5" width={20} height={20}/></li>
    </ul>

  
    

    </div>
   
    

    <div className="flex bg-black 700 pl-96">

<ul className="pl-40 bg-black text-white">
  <li className="text-blue-700 pb-10">Product</li>
<li className="pb-3">Download</li>
<li className="pb-3">Nitro</li>
<li className="pb-3">Status</li>
<li className="pb-3">App Directory</li>
<li>New Mobile Experirence</li></ul>



<ul className="pl-40 bg-black text-white">
  <li className="text-blue-700 pb-10">Company</li>
<li className="pb-3">About</li>
<li className="pb-3">Jobs</li>
<li className="pb-3">Brand</li>
<li className="pb-3">Newsroom</li>
</ul>


<ul className="pl-40 bg-black text-white">
  <li className="text-blue-700 pb-10">
Resources</li>
<li className="pb-3">college</li>
<li className="pb-3">Support</li>
<li className="pb-3">Saftey</li>
<li className="pb-3">Blog</li>
<li className="pb-3">Feedback</li>
<li className="pb-3">Streamkit</li>
<li className="pb-3">Creator</li>
<li className="pb-3">Communuty</li>
<li className="pb-3">Developers</li>
<li className="pb-3">Gaming</li>
<li className="pb-3">Quests</li>
<li className="pb-3">Offical 3rd party merch</li></ul>



<ul className="pl-40 pr-40 bg-black text-white">
  <li className="text-blue-700 pb-10">Policies</li>
<li className="pb-3">Trems</li>
<li className="pb-3">Privacy</li>
<li className="pb-3">Cookie settings</li>
<li className="pb-3">Guidelines</li>
<li className="pb-3">Actknownledgements</li>
<li className="pb-3">License</li>
<li className="pb-3">Company information </li></ul>

  </div>
  <h1 className="text-indigo-500 bg-black pl-40 pr-40 font-extrabold pb-5">______________________________________________________________________________________________________________________________________________________________________________________________________</h1>

  <div className="flex justify-between items-center bg-black pb-20">
   
  <ul className="flex items-center bg-black pl-40 ">
    <li>
    <Image src="/discord.png" alt="discord" width={70} height={70}/>
    </li>
    <li className="text-white font-bold">Discord</li>
  </ul>
  
  <ul className="bg-black ">
    <button className="bg-indigo-500 font-bold text-white rounded-full p-2 mr-48"><li>Sign up</li></button>
  </ul>
  </div>
  

 
        </body>
    </html>
  );
}
